#!/bin/sh

kj p2

echo
echo RMB  "   1  26.174957"
echo RMB  "3387   0.014984"
echo
echo RMB  "16 secs"
echo
echo "--------------------------- 1 threads -----------------------------"
echo
/usr/bin/time -p  ./p2  2100 3200 100 100 100 400 0.015  1
echo
pwd
echo

